// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoPaulo.Data.Context;

namespace ProjetoPaulo.Data.Migrations
{
    [DbContext(typeof(PauloContext))]
    [Migration("20190327165525_Carro")]
    partial class Carro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoPaulo.Data.Entity.Batata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bat_id");

                    b.Property<int>("Cor")
                        .HasColumnName("bat_cor");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("bat_descricao");

                    b.Property<Guid>("TipoBatataId")
                        .HasColumnName("tipo_bat_id");

                    b.HasKey("Id")
                        .HasName("pk_tb_batata");

                    b.HasIndex("TipoBatataId");

                    b.ToTable("tb_batata");
                });

            modelBuilder.Entity("ProjetoPaulo.Data.Entity.Carro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("ProjetoPaulo.Data.Entity.Exemplo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ex_id");

                    b.Property<string>("Descricao")
                        .HasColumnName("ex_descricao");

                    b.HasKey("Id")
                        .HasName("pk_tb_exemplo");

                    b.ToTable("tb_exemplo");
                });

            modelBuilder.Entity("ProjetoPaulo.Data.Entity.Queijo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Queijos");
                });

            modelBuilder.Entity("ProjetoPaulo.Data.Entity.TipoBatata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tipo_bat_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("tipo_bat_descricao");

                    b.HasKey("Id")
                        .HasName("pk_tb_tipo_batata");

                    b.ToTable("tb_tipo_batata");
                });

            modelBuilder.Entity("ProjetoPaulo.Data.Entity.Batata", b =>
                {
                    b.HasOne("ProjetoPaulo.Data.Entity.TipoBatata", "TipoBatata")
                        .WithMany()
                        .HasForeignKey("TipoBatataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
